/**
 * HttpClient
 * HTTP Client
 *
 * OpenAPI spec version: 1.4.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * Do not edit the class manually.
 */
import {expect} from 'chai';
import HttpClientRequests  from '../../src/api/HttpClientRequests';

describe('HttpClientApi', function(){
  let requests;
  beforeEach(function() {
    requests = new HttpClientRequests({
        registerHandler(){
        },
        sendRequest(){
        }
    });

  });


    describe('fetch', function() {
      it('should send request fetch successfully', ()=> {
        //uncomment below and update the code to test fetch
        //return requests.fetch(url: string, method: string, opts: any).then(response=> {
        //  if (error) throw error;
        //  expect(response).to.be();
        //});

      });
    });

});
