/**
 * HttpClient
 * HTTP Client
 *
 * 
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * Do not edit the class manually.
 */
import {expect} from 'chai';
import HttpCLientRequests  from '../../src/api/HttpCLientRequests';

describe('HttpCLientApi', function(){
  let requests;
  beforeEach(function() {
    requests = new HttpCLientRequests({
        registerHandler(){
        },
        sendRequest(){
        }
    });

  });


    describe('request', function() {
      it('should send request request successfully', ()=> {
        //uncomment below and update the code to test request
        //return requests.request(url: string, method: string).then(response=> {
        //  if (error) throw error;
        //  expect(response).to.be();
        //});

      });
    });

});
